package com.mod.mapper;

import org.apache.ibatis.annotations.Param;

import com.mod.bean.GoodsType;
import com.mod.bean.Users;

public interface GoodsTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int insert(GoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int insertSelective(GoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	GoodsType selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int updateByPrimaryKeySelective(GoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goodstype
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int updateByPrimaryKey(GoodsType record);

	int updateByPrimaryKeyChangePk(@Param("g")GoodsType g,@Param("pk")int pk);
}