package com.mod.mapper;

import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;

import org.apache.ibatis.annotations.Flush;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.StatementType;

import com.mod.bean.Users;

public interface UsersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer uid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int insert(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int insertSelective(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	Users selectByPrimaryKey(Integer uid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(Users record);
	int updateByPrimaryKeyChangePk(@Param("u")Users u,@Param("pk")int pk);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Fri Dec 01 13:20:04 CST 2017
	 */
	int updateByPrimaryKey(Users record);
	//@Options(statementType=StatementType.STATEMENT)
	//@Select("SELECT * FROM ${tableName}")
	LinkedList<LinkedHashMap<String,Object>> getTable(@Param("tableName") String tableName);
	@Select("SELECT * FROM users WHERE uname = #{uname} and upwd = #{upwd}")
	Users getUser(@Param("uname") String uname, @Param("upwd") String upwd);
}