package com.mod.mapper;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.mod.bean.AgeInfo;
import com.mod.bean.Users;

public interface UsersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int deleteByPrimaryKey(Integer uid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int insert(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int insertSelective(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	Users selectByPrimaryKey(Integer uid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int updateByPrimaryKeySelective(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Users record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Tue Dec 05 14:45:23 CST 2017
	 */
	int updateByPrimaryKey(Users record);
	int updateByPrimaryKeyChangePk(@Param("u")Users u,@Param("pk")int pk);
	//@Options(statementType=StatementType.STATEMENT)
	//@Select("SELECT * FROM ${tableName}")
	ArrayList<HashMap> getXingInfo(@Param("sum")Integer sum);
	ArrayList<HashMap> getMingInfo(@Param("sum")Integer sum);
	
	ArrayList<AgeInfo> getAgeInfo();
	ArrayList<HashMap> getRegDateInfo(@Param("year")String year);
	LinkedList<LinkedHashMap<String,Object>> getTable(@Param("tableName") String tableName);
	@Select("SELECT * FROM users WHERE uname = #{uname} and upwd = #{upwd}")
	Users getUser(@Param("uname") String uname, @Param("upwd") String upwd);
}